version: '2'

services:
  redis:
    image: redis:alpine
    container_name: redis_db
    command: redis-server --appendonly yes
    ports:
      - 6379:6379
    volumes:
      - temp:/data
    restart: always
    networks:
      - wsredis

networks:
  wsredis:
    driver: bridge
volumes:
  temp:
    driver: local